// Run: node seed-now.js
require('dotenv').config();
const mongoose = require('mongoose');
const Product  = require('./models/Product');

const SEED = [
  { group: '(R)-1-PHENYLETHYLAMINE', make: '', coo: '' },
  { group: '1,2 DIMETHOXY ETHANE', make: 'DIDU', coo: 'China' },
  { group: '1,2 DIMETHOXY ETHANE', make: 'BIDEPHARM', coo: 'China' },
  { group: '1,4-BUTANEDIOL', make: 'DAIREN', coo: 'Taiwan' },
  { group: '1,4-BUTANEDIOL', make: 'NANYA', coo: 'Taiwan' },
  { group: '1,4-BUTANEDIOL', make: 'CHANGMAO', coo: 'China' },
  { group: '1,4-BUTANEDIOL', make: 'NANYA', coo: 'China' },
  { group: '1,4-BUTANEDIOL', make: 'DAIREN', coo: 'China' },
  { group: '1,6-HEXANEDIOL', make: 'BASF', coo: 'Germany' },
  { group: '1,6-HEXANEDIOL', make: 'BOJU', coo: 'China' },
  { group: '1,6-HEXANEDIOL', make: 'YUANLI', coo: 'China' },
  { group: '1-BROMO 3-CHLORO PROPANE', make: 'VYNOVA', coo: 'France' },
  { group: '2-ETHYL HEXYL ACRYLATE', make: 'SATELLITE', coo: 'China' },
  { group: '2-ETHYL HEXANOIC ACID', make: 'PERSTORP', coo: 'Sweden' },
  { group: '2-ETHYL HEXANOIC ACID', make: 'KH NEOCHEM', coo: 'Japan' },
  { group: '2-HYDROXY ETHYL ACRYLATE', make: 'SATELLITE', coo: 'China' },
  { group: '2-METHYL 1,3-PROPANEDIOL', make: 'LYONDELL', coo: 'USA' },
  { group: '2-METHYL TETRAHYDROFURAN', make: 'ZHONGKE', coo: 'China' },
  { group: '2 BUTYNE 1,4 DIOL', make: '', coo: '' },
  { group: '4,4-DIAMINO DIPHENYL METHANE', make: 'WANHUA', coo: 'China' },
  { group: 'ACETONITRILE', make: 'LOTTE', coo: 'Korea' },
  { group: 'ACETONITRILE', make: 'INEOS', coo: 'Belgium' },
  { group: 'ACETONITRILE', make: 'BIDEPHARM', coo: 'China' },
  { group: 'ACETOPHENONE', make: '', coo: 'China' },
  { group: 'ACRYLAMIDE', make: 'SNF', coo: 'France' },
  { group: 'ACRYLIC ACID', make: 'LG', coo: 'Korea' },
  { group: 'ACRYLIC ACID', make: 'BASF', coo: 'Germany' },
  { group: 'ACRYLIC ACID', make: 'DOW', coo: 'USA' },
  { group: 'ACRYLIC ACID', make: 'SATELLITE', coo: 'China' },
  { group: 'ADIPIC ACID', make: 'LANXESS', coo: 'Germany' },
  { group: 'ADIPIC ACID', make: 'INVISTA', coo: 'USA' },
  { group: 'ADIPIC ACID', make: 'ASCEND', coo: 'USA' },
  { group: 'ADIPIC ACID', make: 'RADICI', coo: 'Italy' },
  { group: 'ALLYL ALCOHOL', make: 'LYONDELL', coo: 'USA' },
  { group: 'ALLYL CHLORIDE', make: 'SOLVAY', coo: 'Belgium' },
  { group: 'AMINO ETHYL ETHANOL AMINE', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'AMINO ETHYL ETHANOL AMINE', make: 'BASF', coo: 'Germany' },
  { group: 'AMINO ETHYL PIPERAZINE', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'AMINO ETHYL PIPERAZINE', make: 'BASF', coo: 'Germany' },
  { group: 'AMMONIUM BIFLUORIDE', make: '', coo: 'China' },
  { group: 'AMMONIUM FLUORIDE', make: '', coo: 'China' },
  { group: 'AMMONIUM THIOCYANATE', make: '', coo: 'China' },
  { group: 'BENZALDEHYDE', make: '', coo: 'China' },
  { group: 'BENZALDEHYDE', make: 'EMERALD', coo: 'USA' },
  { group: 'BENZYL ALCOHOL', make: '', coo: 'China' },
  { group: 'BENZYL ALCOHOL', make: 'EMERALD', coo: 'USA' },
  { group: 'BENZYL CHLORIDE', make: '', coo: 'China' },
  { group: 'BISPHENOL A', make: 'KUMHO', coo: 'Korea' },
  { group: 'BISPHENOL A', make: 'SINOPEC', coo: 'China' },
  { group: 'BISPHENOL A', make: 'MITSUI', coo: 'Japan' },
  { group: 'BORIC ACID', make: '', coo: 'China' },
  { group: 'BORIC ACID', make: 'ETI MADEN', coo: 'Turkey' },
  { group: 'BROMIDE COMPOUNDS', make: '', coo: 'China' },
  { group: 'BUTYL ACRYLATE', make: 'BASF', coo: 'Germany' },
  { group: 'BUTYL ACRYLATE', make: 'LG', coo: 'Korea' },
  { group: 'BUTYL ACRYLATE', make: 'SATELLITE', coo: 'China' },
  { group: 'BUTYL GLYCOL', make: 'BASF', coo: 'Germany' },
  { group: 'BUTYL GLYCOL', make: 'DOW', coo: 'USA' },
  { group: 'BUTYL GLYCOL', make: 'SHELL', coo: 'Netherlands' },
  { group: 'CALCIUM CHLORIDE', make: '', coo: 'China' },
  { group: 'CAPROLACTAM', make: 'BASF', coo: 'Germany' },
  { group: 'CAPROLACTAM', make: 'DSM', coo: 'Netherlands' },
  { group: 'CAPROLACTAM', make: 'SINOPEC', coo: 'China' },
  { group: 'CAUSTIC SODA FLAKES', make: '', coo: 'China' },
  { group: 'CAUSTIC SODA FLAKES', make: 'OLIN', coo: 'USA' },
  { group: 'CAUSTIC SODA LIQUID', make: '', coo: 'China' },
  { group: 'CHLOROACETIC ACID', make: '', coo: 'China' },
  { group: 'CHLOROFORM', make: '', coo: 'China' },
  { group: 'CITRIC ACID', make: '', coo: 'China' },
  { group: 'CYCLOHEXANE', make: 'SHELL', coo: 'Netherlands' },
  { group: 'CYCLOHEXANE', make: '', coo: 'China' },
  { group: 'CYCLOHEXANONE', make: 'BASF', coo: 'Germany' },
  { group: 'CYCLOHEXANONE', make: '', coo: 'China' },
  { group: 'CYCLOHEXANOL', make: '', coo: 'China' },
  { group: 'DCPD (DICYCLOPENTADIENE)', make: '', coo: 'China' },
  { group: 'DCPD (DICYCLOPENTADIENE)', make: '', coo: 'Korea' },
  { group: 'DEA (DIETHANOLAMINE)', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'DEA (DIETHANOLAMINE)', make: 'BASF', coo: 'Germany' },
  { group: 'DEA (DIETHANOLAMINE)', make: '', coo: 'China' },
  { group: 'DIACETONE ALCOHOL', make: '', coo: 'China' },
  { group: 'DIETHYL CARBONATE', make: '', coo: 'China' },
  { group: 'DIETHYLENE GLYCOL', make: 'SHELL', coo: 'Netherlands' },
  { group: 'DIETHYLENE GLYCOL', make: 'MEGlobal', coo: 'USA' },
  { group: 'DIETHYLENE GLYCOL', make: '', coo: 'China' },
  { group: 'DIISONONYL PHTHALATE', make: 'BASF', coo: 'Germany' },
  { group: 'DIISONONYL PHTHALATE', make: 'AEKYUNG', coo: 'Korea' },
  { group: 'DIMETHYL CARBONATE', make: '', coo: 'China' },
  { group: 'DIMETHYL SULFOXIDE', make: '', coo: 'China' },
  { group: 'DIPROPYLENE GLYCOL', make: 'DOW', coo: 'USA' },
  { group: 'DIPROPYLENE GLYCOL', make: '', coo: 'China' },
  { group: 'DODECYL BENZENE SULFONIC ACID', make: '', coo: 'China' },
  { group: 'EPICHLOROHYDRIN', make: 'SOLVAY', coo: 'Belgium' },
  { group: 'EPICHLOROHYDRIN', make: '', coo: 'China' },
  { group: 'ETHANOL', make: '', coo: 'India' },
  { group: 'ETHYL ACETATE', make: '', coo: 'China' },
  { group: 'ETHYL ACETATE', make: '', coo: 'India' },
  { group: 'ETHYLENE GLYCOL', make: 'MEGlobal', coo: 'USA' },
  { group: 'ETHYLENE GLYCOL', make: 'SHELL', coo: 'Netherlands' },
  { group: 'ETHYLENE GLYCOL', make: '', coo: 'China' },
  { group: 'ETHYLENE OXIDE', make: 'BASF', coo: 'Germany' },
  { group: 'ETHYLENE OXIDE', make: 'SHELL', coo: 'Netherlands' },
  { group: 'FORMALDEHYDE', make: '', coo: 'India' },
  { group: 'FORMIC ACID', make: 'BASF', coo: 'Germany' },
  { group: 'FORMIC ACID', make: '', coo: 'China' },
  { group: 'FURFURAL', make: '', coo: 'China' },
  { group: 'FURFURYL ALCOHOL', make: '', coo: 'China' },
  { group: 'GLACIAL ACETIC ACID', make: 'CELANESE', coo: 'USA' },
  { group: 'GLACIAL ACETIC ACID', make: '', coo: 'China' },
  { group: 'GLACIAL ACETIC ACID', make: '', coo: 'India' },
  { group: 'GLUTARALDEHYDE', make: 'DOW', coo: 'USA' },
  { group: 'GLUTARALDEHYDE', make: 'BASF', coo: 'Germany' },
  { group: 'GLYCERINE', make: '', coo: 'China' },
  { group: 'GLYCERINE', make: '', coo: 'Malaysia' },
  { group: 'HEXAMINE', make: '', coo: 'China' },
  { group: 'HYDRAZINE HYDRATE', make: '', coo: 'China' },
  { group: 'HYDROCHLORIC ACID', make: '', coo: 'India' },
  { group: 'HYDROGEN PEROXIDE', make: 'SOLVAY', coo: 'Belgium' },
  { group: 'HYDROGEN PEROXIDE', make: '', coo: 'India' },
  { group: 'ISOBUTYL ALCOHOL', make: '', coo: 'China' },
  { group: 'ISOBUTYL ALCOHOL', make: 'BASF', coo: 'Germany' },
  { group: 'ISOPROPYL ALCOHOL', make: '', coo: 'China' },
  { group: 'ISOPROPYL ALCOHOL', make: 'SHELL', coo: 'Netherlands' },
  { group: 'ISOPROPYL ALCOHOL', make: 'DOW', coo: 'USA' },
  { group: 'LACTIC ACID', make: '', coo: 'China' },
  { group: 'LACTIC ACID', make: 'PURAC', coo: 'Netherlands' },
  { group: 'MALEIC ANHYDRIDE', make: '', coo: 'China' },
  { group: 'MALEIC ANHYDRIDE', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'MEA (MONOETHANOLAMINE)', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'MEA (MONOETHANOLAMINE)', make: 'BASF', coo: 'Germany' },
  { group: 'MEA (MONOETHANOLAMINE)', make: '', coo: 'China' },
  { group: 'METHANOL', make: '', coo: 'China' },
  { group: 'METHANOL', make: '', coo: 'Middle East' },
  { group: 'METHYL ACETATE', make: '', coo: 'China' },
  { group: 'METHYL ACRYLATE', make: 'BASF', coo: 'Germany' },
  { group: 'METHYL ETHYL KETONE', make: '', coo: 'China' },
  { group: 'METHYL ETHYL KETONE', make: 'SHELL', coo: 'Netherlands' },
  { group: 'METHYL ISOBUTYL KETONE', make: '', coo: 'China' },
  { group: 'METHYL ISOBUTYL KETONE', make: 'SHELL', coo: 'Netherlands' },
  { group: 'METHYL METHACRYLATE', make: 'MITSUBISHI', coo: 'Japan' },
  { group: 'METHYL METHACRYLATE', make: '', coo: 'China' },
  { group: 'MONO PROPYLENE GLYCOL', make: 'DOW', coo: 'USA' },
  { group: 'MONO PROPYLENE GLYCOL', make: 'SHELL', coo: 'Netherlands' },
  { group: 'MONO PROPYLENE GLYCOL', make: '', coo: 'China' },
  { group: 'MORPHOLINE', make: 'BASF', coo: 'Germany' },
  { group: 'MORPHOLINE', make: '', coo: 'China' },
  { group: 'N BUTYL ALCOHOL', make: 'BASF', coo: 'Germany' },
  { group: 'N BUTYL ALCOHOL', make: 'OXEA', coo: 'Germany' },
  { group: 'N BUTYL ALCOHOL', make: '', coo: 'China' },
  { group: 'N-HEPTANE', make: '', coo: 'China' },
  { group: 'N-HEXANE', make: '', coo: 'China' },
  { group: 'N-METHYL 2 PYRROLIDONE', make: 'BASF', coo: 'Germany' },
  { group: 'N-METHYL 2 PYRROLIDONE', make: '', coo: 'China' },
  { group: 'NITRIC ACID', make: '', coo: 'India' },
  { group: 'NEOPENTYL GLYCOL', make: 'BASF', coo: 'Germany' },
  { group: 'NEOPENTYL GLYCOL', make: 'PERSTORP', coo: 'Sweden' },
  { group: 'NEOPENTYL GLYCOL', make: '', coo: 'China' },
  { group: 'NONYL PHENOL', make: '', coo: 'China' },
  { group: 'OXALIC ACID', make: '', coo: 'China' },
  { group: 'PARAFORMALDEHYDE', make: '', coo: 'China' },
  { group: 'PENTAERYTHRITOL', make: 'PERSTORP', coo: 'Sweden' },
  { group: 'PENTAERYTHRITOL', make: '', coo: 'China' },
  { group: 'PERACETIC ACID', make: 'SOLVAY', coo: 'Belgium' },
  { group: 'PERACETIC ACID', make: '', coo: 'China' },
  { group: 'PHOSPHORIC ACID', make: '', coo: 'China' },
  { group: 'PHTHALIC ANHYDRIDE', make: '', coo: 'China' },
  { group: 'PHTHALIC ANHYDRIDE', make: 'AEKYUNG', coo: 'Korea' },
  { group: 'PIPERAZINE', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'PIPERAZINE', make: 'BASF', coo: 'Germany' },
  { group: 'PIPERAZINE', make: '', coo: 'China' },
  { group: 'POLYETHYLENE GLYCOL', make: 'DOW', coo: 'USA' },
  { group: 'POLYETHYLENE GLYCOL', make: 'SHELL', coo: 'Netherlands' },
  { group: 'POLYETHYLENE GLYCOL', make: '', coo: 'China' },
  { group: 'POTASSIUM CARBONATE', make: '', coo: 'China' },
  { group: 'POTASSIUM HYDROXIDE', make: '', coo: 'China' },
  { group: 'PROPIONIC ACID', make: 'BASF', coo: 'Germany' },
  { group: 'PROPIONIC ACID', make: 'PERSTORP', coo: 'Sweden' },
  { group: 'PROPYLENE GLYCOL METHYL ETHER', make: 'DOW', coo: 'USA' },
  { group: 'PROPYLENE GLYCOL METHYL ETHER', make: '', coo: 'China' },
  { group: 'PROPYLENE OXIDE', make: 'BASF', coo: 'Germany' },
  { group: 'PROPYLENE OXIDE', make: 'DOW', coo: 'USA' },
  { group: 'PYRIDINE', make: '', coo: 'China' },
  { group: 'SODIUM BICARBONATE', make: '', coo: 'China' },
  { group: 'SODIUM CARBONATE', make: '', coo: 'China' },
  { group: 'SODIUM CHLORATE', make: '', coo: 'China' },
  { group: 'SODIUM FORMATE', make: '', coo: 'China' },
  { group: 'SODIUM GLUCONATE', make: '', coo: 'China' },
  { group: 'SODIUM HYPOCHLORITE', make: '', coo: 'India' },
  { group: 'SODIUM METABISULPHITE', make: '', coo: 'China' },
  { group: 'SODIUM SULPHATE', make: '', coo: 'China' },
  { group: 'SODIUM SULPHITE', make: '', coo: 'China' },
  { group: 'SODIUM THIOSULPHATE', make: '', coo: 'China' },
  { group: 'SORBITOL', make: '', coo: 'China' },
  { group: 'STEARIC ACID', make: '', coo: 'Malaysia' },
  { group: 'STYRENE MONOMER', make: 'SHELL', coo: 'Netherlands' },
  { group: 'STYRENE MONOMER', make: '', coo: 'China' },
  { group: 'SUCCINIC ACID', make: '', coo: 'China' },
  { group: 'SULPHURIC ACID', make: '', coo: 'India' },
  { group: 'TEA (TRIETHANOLAMINE)', make: 'HUNTSMAN', coo: 'USA' },
  { group: 'TEA (TRIETHANOLAMINE)', make: 'BASF', coo: 'Germany' },
  { group: 'TEA (TRIETHANOLAMINE)', make: '', coo: 'China' },
  { group: 'TETRAHYDROFURAN', make: 'BASF', coo: 'Germany' },
  { group: 'TETRAHYDROFURAN', make: '', coo: 'China' },
  { group: 'TOLUENE', make: '', coo: 'China' },
  { group: 'TOLUENE', make: '', coo: 'India' },
  { group: 'TRIMETHYLOLPROPANE', make: 'PERSTORP', coo: 'Sweden' },
  { group: 'TRIMETHYLOLPROPANE', make: 'BASF', coo: 'Germany' },
  { group: 'TRIMETHYLOLPROPANE', make: '', coo: 'China' },
  { group: 'UREA', make: '', coo: 'India' },
  { group: 'UREA', make: '', coo: 'China' },
  { group: 'VINYL ACETATE MONOMER', make: 'CELANESE', coo: 'USA' },
  { group: 'VINYL ACETATE MONOMER', make: '', coo: 'China' },
  { group: 'XYLENE', make: '', coo: 'China' },
  { group: 'XYLENE', make: '', coo: 'India' },
  { group: 'ZINC CHLORIDE', make: '', coo: 'China' },
  { group: 'ZINC SULPHATE', make: '', coo: 'China' },
];

async function run() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  // Delete all existing products and re-insert fresh
  await Product.deleteMany({});
  console.log('Cleared existing products');

  const docs = SEED.map(p => ({
    group: p.group, name: p.group,
    make: p.make || '', coo: p.coo || '',
    grade: '', purity: '', itemPackage: '', unit: 'kg', isActive: true,
  }));

  await Product.insertMany(docs);
  console.log(`✓ Inserted ${docs.length} products successfully`);

  await mongoose.disconnect();
  process.exit(0);
}

run().catch(err => { console.error('Error:', err.message); process.exit(1); });
